### PR TITLE
Tests, check before proceed actor

### PR DESCRIPTION
**Pull request by ashl1**
BREAKING CHANGES!

[a] add tests
[m] full rewrite the code. Proceed actors only if the part of state has been changed
[m] export only subscribe(actors) with ability to get single actor or actors like reducers

### CODE REVIEW

**Comment by lronhoj** [comment]
Looks good. I've invited you to become collaborator since I'm obviously not maintaining this. So feel free to run it as your own.

**Comment by lronhoj** [comment]
If you have an npm user i can add you as maintainer so you can make releases.

**Comment by ashl1** [comment]
My NPM account: ashl1
Thank you

ср, 5 июл 2017 г., 10:15 Lars Rønhøj <notifications@github.com>:

**Comment by ashl1** [comment]
@Ironhoj Newer version 1.0.0 in NPM has old compiled version. I changed only src/ files in the PR because lib/ directory is .gitignore'd

**Comment by lronhoj** [comment]
You are absolutely right. Building should probably be added as a pre publish hook. I made a minor release which is build.

You are added as owner to the npm package.

**Pull request merged**
